language: python

python:
  - 3.5

install:
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/use-conda-with-travis-ci.html
  - sudo apt-get update
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - source "$HOME/miniconda/etc/profile.d/conda.sh"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - type pip
  - pip install -r requirements.txt

script:
  # case when install.py is in the current dir
  - bash test.sh .
  # case when install.py is one level down
  - bash test.sh ..
  # also test when cloning
  - bash test_git.sh $TRAVIS_COMMIT
  # run tests/ (do not just use "pytest" as that will run template tests/)
  - pytest tests/