meta:
  # load all task.source relative to src/package_name/. If removed, relative
  # paths in task.source will be so to the parent directory of this file.
  source_loader:
    module: package_name
  
  jupyter_hot_reload: True

  import_tasks_from: pipeline-features.yaml

tasks:
  - source: package_name.tasks.raw.get
    product: products/raw/dataset.parquet

  - source: notebooks/plot.py
    product: products/report.html
